export const top_selling = [
  {
    img: "/houserent3.jpg",
    description: "5 bedroom Terrace for sale",
    price: 2500000000,
    discount: 260000000,
    bedroom: 5,
    bathrooms: 5,
    property_type: "Terrace",
    market_status: "Now Selling",
    total_area: "2350Sq.m",
    covered_area: "2400Sq.m",
  },
  {
    img: "/housetop9.jpg",
    description: "4 bedroom Terrace for sale",
    price: 1500000000,
    discount: 2000000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Terrace",
    market_status: "Now Selling",
    total_area: "1550Sq.m",
    covered_area: "16000Sq.m",
  },
  {
    img: "/housetop10.jpg",
    description: "3 bedroom flat Apartment",
    price: 500000000,
    discount: 600000000,
    bedroom: 3,
    bathrooms: 3,
    property_type: "Flat",
    market_status: "Now Selling",
    total_area: "1350Sq.m",
    covered_area: "1400Sq.m",
  },
  {
    img: "/housetop7.jpg",
    description: "4 bedroom Duplex for sale",
    price: 1000000000,
    discount: 1400000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Duplex",
    market_status: "Now Selling",
    total_area: "1750Sq.m",
    covered_area: "1800Sq.m",
  },
  {
    img: "/housetop5.jpg",
    description: "5 bedroom Terrace for sale",
    price: 2000000000,
    discount: 1600000000,
    bedroom: 5,
    bathrooms: 5,
    property_type: "Terrace",
    market_status: "Now Selling",
    total_area: "1350Sq.m",
    covered_area: "1400Sq.m",
  },
  {
    img: "/housetop6.jpg",
    description: "8 bedroom Terrace for sale",
    price: 7000000000,
    discount: 8000000000,
    bedroom: 8,
    bathrooms: 8,
    property_type: "Terrace",
    market_status: "Now Selling",
    total_area: "3350Sq.m",
    covered_area: "4400Sq.m",
  },
  {
    img: "/housetop9.jpg",
    description: "6 bedroom Terrace for sale",
    price: 6500000000,
    discount: 7000000000,
    bedroom: 6,
    bathrooms: 6,
    property_type: "Terrace",
    market_status: "Now Selling",
    total_area: "2750Sq.m",
    covered_area: "3000Sq.m",
  },
  {
    img: "/housetop2.jpg",
    description: "6 bedroom Terrace for sale",
    price: 3500000000,
    discount: 4000000000,
    bedroom: 6,
    bathrooms: 6,
    property_type: "Terrace",
    market_status: "Now Selling",
    total_area: "2000Sq.m",
    covered_area: "2500Sq.m",
  },
];
export const limited_stock = [
  {
    img: "/houserent1.jpg",
    description: "1 bedroom house shortlet",
    price: 450000,
    discount: 500000,
    bedroom: 1,
    bathrooms: 1,
    property_type: "Bungalow",
    market_status: "Now Renting",
    total_area: "350Sq.m",
    covered_area: "400Sq.m",
  },
  {
    img: "/houserent5.jpg",
    description: "4 bedroom detached for rent",
    price: 7000000,
    discount: 8000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Semi Detached",
    market_status: "Now Renting",
    total_area: "500Sq.m",
    covered_area: "600Sq.m",
  },
  {
    img: "/houserent3.jpg",
    description: "4 bedroom flat apt for rent",
    price: 5500000,
    discount: 6000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Flat",
    market_status: "Now Renting",
    total_area: "2500Sq.m",
    covered_area: "3000Sq.m",
  },
  {
    img: "/houserent6.jpg",
    description: "4 bedroom flat apt for rent",
    price: 6000000,
    discount: 7000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Flat",
    market_status: "Now Renting",
    total_area: "2000Sq.m",
    covered_area: "2500Sq.m",
  },
  {
    img: "/houserent7.jpg",
    description: "1 bedroom house shortlet",
    price: 2500000,
    discount: 3000000,
    bedroom: 1,
    bathrooms: 1,
    property_type: "Bungalow",
    market_status: "Now Renting",
    total_area: "350Sq.m",
    covered_area: "450Sq.m",
  },
  {
    img: "/houserent9.jpg",
    description: "4 bedroom flat apt for sale",
    price: 4500000,
    discount: 5000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Flat",
    market_status: "Now Renting",
    total_area: "1500Sq.m",
    covered_area: "2000Sq.m",
  },
  {
    img: "/houserent10.jpg",
    description: "4 bedroom flat apt for rent",
    price: 5000000,
    discount: 6000000,
    bedroom: 4,
    bathrooms: 4,
    property_type: "Flat",
    market_status: "Now Renting",
    total_area: "2000Sq.m",
    covered_area: "2300Sq.m",
  },
  {
    img: "/houserent11.jpg",
    description: "1 bedroom house shortlet",
    price: 500000,
    discount: 600000,
    bedroom: 1,
    bathrooms: 1,
    property_type: "Bungalow",
    market_status: "Renting",
    total_area: "350Sq.m",
    covered_area: "400Sq.m",
  },
];
